version: "3.3"
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./dbData:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - ./.env
    environment:
      PMA_HOST: mysql 
      PMA_PORT: 3306
    restart: always
    ports:
      - "80:80"
